export TYPEORM_CONNECTION=postgres  
export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
export TYPEORM_HOST=dbcicdproject.cg35u2xttsew.us-east-1.rds.amazonaws.com
export TYPEORM_PORT= 5432
export TYPEORM_USERNAME=postgres
export TYPEORM_PASSWORD= postgres
export TYPEORM_DATABASE= project3db
export TYPEORM_MIGRATIONS= ./src/migrations/*.ts
export TYPEORM_MIGRATIONS_DIR= ./src/migrations
